In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
from sklearn.datasets import fetch_20newsgroups

In [10]:
train=fetch_20newsgroups(subset='train')
train.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [11]:
test=fetch_20newsgroups(subset='test')
test.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [12]:
train.target_names[train.target[0]]

'rec.autos'

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
CountVectorizer = CountVectorizer(max_features=1000)
vect  = CountVectorizer.fit_transform(train.data)
vect = vect.toarray()

In [15]:
vect

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
X = vect

In [35]:
y = train.target

In [36]:
X.shape

(7532, 1000)

In [37]:
y.shape

(7532,)

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
from os import XATTR_CREATE
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [33]:
y_pred = model.predict(X_test)

In [34]:
from sklearn.metrics import accuracy_score, confusion_matrix
acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

In [35]:
acc

0.6703490941228458

In [36]:
cm

array([[72,  0,  0,  0,  1,  0,  0,  0,  6,  1,  1,  0,  0,  2,  1,  2,
         1,  1,  2,  7],
       [ 0, 71,  0,  6,  9,  5,  2,  4,  1,  0,  0,  0,  5,  1,  0,  0,
         0,  0,  0,  0],
       [ 0, 35,  3, 43,  3, 20,  5,  2,  1,  0,  0,  0,  3,  0,  0,  0,
         0,  0,  0,  0],
       [ 0, 12,  0, 70, 18,  2, 11,  2,  3,  0,  0,  0,  3,  1,  0,  0,
         0,  0,  1,  0],
       [ 0,  5,  0, 11, 86,  0,  8,  1,  3,  0,  0,  0,  9,  2,  1,  0,
         0,  0,  0,  0],
       [ 1, 13,  0,  3,  4, 78,  3,  0,  0,  0,  0,  1,  3,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  3,  1,  0, 94,  5,  2,  1,  0,  0,  2,  0,  0,  0,
         0,  0,  0,  1],
       [ 0,  1,  0,  2,  5,  1,  6, 99, 13,  4,  0,  0,  5,  1,  0,  0,
         1,  0,  1,  0],
       [ 0,  1,  0,  0,  5,  1,  8,  4, 98,  0,  0,  0,  0,  2,  1,  0,
         0,  0,  0,  2],
       [ 0,  1,  0,  0,  1,  0,  2,  1,  4, 82,  5,  0,  2,  2,  1,  0,
         1,  0,  0,  0],
       [ 0,  0,  0,  0,  2,  1

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
docs = [
    "I love programming in Python.",
    "Python is great for data science.",
    "Machine learning is a subset of data science."
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(docs)
print(vectorizer.get_feature_names_out())
X.toarray()

['data' 'for' 'great' 'in' 'is' 'learning' 'love' 'machine' 'of'
 'programming' 'python' 'science' 'subset']


array([[0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1]])

In [53]:
test = fetch_20newsgroups(subset='test')
test.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']